controllers/games_controller.py
import pdb
from flask import Flask, render_template, request, redirect
from flask import Blueprint
from sqlalchemy import or_
from db.run_sql import run_sql
from services.database import db
from models.game import Game
from models.team import Team
import repositories.game_repository as game_repository
import repositories.team_repository as team_repository


games_blueprint = Blueprint("games", __name__)

# List all games
# All Teams
@games_blueprint.route('/games')
def games():
    games = Game.query.order_by(Game.game_date).all()
    return render_template('games/index.html', games=games)

@games_blueprint.route('/games/<id>', methods = ['GET'])
def show(id):
    game = Game.query.filter(Game.id==id).one_or_none()
    team1 = game.team_1
    team2 = game.team_2
    return render_template('games/show.html', game=game, team_1=team1, team_2=team2)

#SHOW ONE GAME
@games_blueprint.route("/games/new", methods=['GET'])
def new_game():
    teams = Team.query.order_by(Team.name).all()
    games = Game.query.order_by(Game.game_date).all()
    return render_template('games/new.html', games=games, teams=teams)

#CREATE NEW GAME
#Post New Game
@games_blueprint.route("/games",  methods=['POST'])
def create_team():
    teams = Team.query.order_by(Team.name).all()
    if request.method == 'POST':
        team_1 = request.form['team_1']
        print(team_1)
        team_2 = request.form['team_2']
        print(team_2)
        team_1_runs = int(request.form['team_1_runs'])
        team_2_runs = int(request.form['team_2_runs'])
        game_date = request.form['game_date']
        # if team_1 or team_2 == '':
        #     print("hello")
        #     return render_template('games/new.html')
        data = Game(team_1, team_2, team_1_runs, team_2_runs, game_date)
        print(data)
        db.session.add(data)

        team_1_update = Team.query.filter(Team.name==team_1).one_or_none()
        team_2_update = Team.query.filter(Team.name==team_2).one_or_none()

        if team_1_runs > team_2_runs:
            team_1_update.points +=2
        elif team_2_runs > team_1_runs:
            team_2_update.points +=2
        else:
            team_1_update.points +=1
            team_2_update.points +=1
        db.session.commit()
        return redirect('/games')
    return render_template('games/new.html', teams=teams)



#Show games associated with team
@games_blueprint.route("/team-games/<id>", methods=['GET'])
def show_game_for_team(id):
    team = Team.query.filter(Team.id == id).one_or_none()
    games = Game.query.filter(or_(Game.team_1 == team.name, Game.team_2 == team.name))
    print(games)
    # games = games1 + games2
    return render_template('games/team.html', games = games)



# EDIT GET
@games_blueprint.route("/games/<id>/edit", methods=['GET'])
def edit_game(id):
    game = Game.query.filter(Game.id==id).one_or_none()
    teams = Team.query.order_by(Team.name).all()
    return render_template('games/edit.html', teams=teams, game=game)

# EDIT POST
# @games_blueprint.route("/games/<id>", methods=['POST'])
# def update_game(id):
#     team_1 = team_repository.select(request.form['team_1_id'])
#     team_2 = team_repository.select(request.form['team_2_id'])
#     team_1_runs = request.form['team_1_runs']
#     team_2_runs = request.form['team_2_runs']
#     game_date = request.form['game_date']

#     game = Game(team_1, team_2, team_1_runs, team_2_runs, game_date, id)
#     game_repository.update(game)
#     return redirect('/games')

# EDIT POST
@games_blueprint.route("/games/<id>", methods=['POST'])
def update_game(id):
    game_to_update = Game.query.filter(Game.id==id).one_or_none()
    if request.method == 'POST':
        game_to_update.team_1 = game_to_update.team_1
        game_to_update.team_2 = game_to_update.team_2
        game_to_update.team_1_runs = request.form['team_1_runs']
        game_to_update.team_2_runs = request.form['team_2_runs']
        game_to_update.game_date = request.form['game_date']
        try:
            db.session.commit()
            return redirect('/games')
        except:
            print("error")
            return redirect('/games')
          
    return render_template('games/edit.html')


#DELETE
@games_blueprint.route("/games/<id>/delete", methods=['POST'])
def delete_team(id):
    games = Game.query.all()
    game = Game.query.filter(Game.id==id).one_or_none()
    team_1_update = Team.query.filter(Team.name==game.team_1).one_or_none()
    team_2_update = Team.query.filter(Team.name==game.team_2).one_or_none()

    try:
        db.session.delete(game)
        db.session.commit()
        if game.team_1_runs > game.team_2_runs:
            team_1_update.points -=2
        elif game.team_2_runs > game.team_1_runs:
            team_2_update.points -=2
        else:
            team_1_update.points -= 1
            team_2_update.points -= 1
        db.session.commit()
        return redirect('/games')
    except:
        return redirect('/games')
    
    

controllers/table_controller.py
from flask import Flask, render_template, request, redirect
from flask import Blueprint
from models.team import Team
import repositories.team_repository as team_repository


table_blueprint = Blueprint("table", __name__)

@table_blueprint.route('/table')
def show_table():
    teams_1 = Team.query.order_by(Team.points.desc()).filter(Team.group_id == 1).all()
    teams_2 = Team.query.order_by(Team.points.desc()).filter(Team.group_id == 2).all()
    positions = [1,2,3,4,5,6]
    return render_template('table/index.html', teams_1=teams_1, teams_2=teams_2, positions=positions)

controllers/teams_controller.py
import pdb
from flask import Flask, render_template, request, redirect
from flask import Blueprint
from services.database import db

from models.team import Team

import repositories.team_repository as team_repository
import repositories.game_repository as game_repository

teams_blueprint = Blueprint("teams", __name__)


# All Teams
@teams_blueprint.route('/teams')
def teams():
    teams = Team.query.order_by(Team.name).all()
  
    return render_template('teams/index.html', teams=teams)

@teams_blueprint.route('/teams/<id>', methods = ['GET'])
def show(id):
    team = Team.query.filter(Team.id==id).one_or_none()
    return render_template('teams/show.html', team=team)

# CREATE
#Create new Game
# dfjkasdbfkj
@teams_blueprint.route("/teams/new", methods=['GET'])
def new_team():
    teams = Team.query.all()
    return render_template("teams/new.html", teams=teams)


#Post New Game
@teams_blueprint.route("/teams",  methods=['POST'])
def create_team():
    if request.method == 'POST':
        team_name = request.form['team_name']
        team_points = int(request.form['team_points'])
        team_group_id = int(request.form['group_id'])
        if team_name == '':
            return render_template('teams/new.html')
        if db.session.query(Team).filter(Team.name == team_name).count() == 0:
            data = Team(team_name, team_points, team_group_id)
            db.session.add(data)
            db.session.commit()
            return redirect('/teams')
        return render_template('teams/new.html')


# EDIT GET
@teams_blueprint.route("/teams/<id>/edit", methods=['GET'])
def edit_game(id):
    team = Team.query.filter(Team.id==id).one_or_none()
    return render_template('teams/edit.html', team=team)

# EDIT POST
@teams_blueprint.route("/teams/<id>", methods=['POST'])
def update_game(id):
    team_to_update = Team.query.filter(Team.id==id).one_or_none()
    if request.method == 'POST':
        team_to_update.name = team_to_update.name
        team_to_update.points = request.form['team_points']
        team_to_update.group_id = request.form['group_id']
        try:
            db.session.commit()
            return redirect('/teams')
        except:
            print("error")
            return redirect('/teams')
          
    return render_template('teams/edit.html')

#DELETE
@teams_blueprint.route("/teams/<id>/delete", methods=['POST'])
def delete_team(id):
    teams = Team.query.order_by(Team.name).all()
    team = Team.query.filter(Team.id==id).one_or_none()
    try:
        db.session.delete(team)
        db.session.commit()
        return redirect('/teams')
    except:
        return redirect('/teams')


    

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CWC Group Stage</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style/style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="app-grid-container">
        <header class="header">
            <nav>
                <img src="{{ url_for('static', filename='images/cwciInsider.png') }}" alt="logo" class = "logo">
                   
                <ul class="nav-list">
                    <li class="header-list-item"><a href="">Quick Links</a></li>
                    <li class="header-list-item"><a href="">Contact</a></li>
                    <li class="header-list-item"><a href="">Terms and Conditions</a></li>
                    <li class="header-list-item"><a href="/">Home</a></li>
                </ul>
            </nav>
        </header>
        <nav class="content-nav">
            <div class="content-nav-wrapper">
                <ul class="content-nav-list">
                    <li class="content-nav-item"><a href="{{ url_for('teams.teams') }}">Teams</a></li>
                    <li class="content-nav-item"><a href="{{ url_for('games.games') }}">Matches</a></li>
                    <li class="content-nav-item"><a href="{{ url_for('games.new_game') }}">New Match</a></li>
                    <li class="content-nav-item"><a href="{{ url_for('table.show_table') }}">League Table</a></li>
                </ul>
            </div>
        </nav>
        <hr>
    
        
        
        <main class="main">
            {% block content %}
            {% endblock %}
            {% block table %}
            {% endblock %}
            {% block team %}
            {% endblock %}
            {% block all_teams %}
            {% endblock %}
            {% block new_team_form %}
            {% endblock %}
            {% block hello %}
            {% endblock %}
        </main>
            
        <footer class="footer">
            <div class="footer-text">
                <h6>
                    &copy Lorem ipsum dolor sit amet: <em>2021</em>
                </h6>
            </div>
        </footer>
    </div>

    
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="home-page">
    <div class="jumbotron-img">
        <div class="jumbotron-filter">
            <div class="jumbotron-overlay-text">
                <h1>CWC Insider</h1>
                <p>Welcome to CWC Insider. Click the button below to see the current standings</p><br>
                <a href="/table"><button class="index-btn">See the Table
                </button></a>
            </div>
        </div>
    </div>
</div>
{% endblock %}